# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

include:
  - _pages
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
keep_files:
  - assets
incremental: true

minimal_mistakes_skin : default
locale                : zh-CN
title                 : "Qliphoth Tech"
subtitle              : "1492 A.A."
name                  : "Alias Qli"
description           : "我深知这不过是权宜之计。"
url                   : "https://alias.qliphoth.tech"
repository            : "AliasQli/aliasqli.github.io"
timezone              : "Asia/Shanghai"
permalink             : none
search                : true

head_scripts:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout  : single
      toc     : true
      related : true
      comments: true
  - scope:
      path: ""
      type: pages
    values:
      layout        : single
      classes       : wide
      author_profile: true
  - scope:
      path: ""
      type: tag
    values:
      layout        : single
      classes       : wide
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      layout        : single
      classes       : wide
      author_profile: true


# category_archive:
#   type: liquid
#   path: /cat/
# tag_archive:
#   type: liquid
#   path: /tags/
# year_archive:
#   type: liquid
#   path: /posts/
category_archive:
  type: jekyll-archives
  path: /cat/
tag_archive:
  type: jekyll-archives
  path: /tags/
year_archive:
  type: jekyll-archives
  path: /posts/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /cat/:name/
    tag: /tags/:name/

author:
  name    : "Alias Qli"
  avatar  : "/assets/images/AliasQli.jpg"
  location: "The Moor, Gusto"
  links   :
    - label : "Email"
      icon  : "fas fa-fw fa-envelope-square"
      url   : "mailto:2576814881@qq.com"
    - label : "GitHub"
      icon  : "fab fa-fw fa-github"
      url   : "https://github.com/AliasQli"

comments:
  provider: giscus
  giscus:
    repo_id           : "R_kgDOGiUXrQ"
    category_name     : Announcements
    category_id       : "DIC_kwDOGiUXrc4CAsae"
    discussion_term   : title
    reactions_enabled : 1
    theme             : light
